### ISSUE TITLE
An error occurs during the project build via mk in the plan 9 system

### ISSUE THREAD

**Issue by katamaranov** [telephil9/nc#1]
error - input.c:141 name not declared: Knack
mk: 8c -FTVw input.c  : exit status=rc 277: 8c 279: error
after deleting the ```else if(k == Knack){ len=0 }``` block from the input.c file, the project is successfully built

**Comment by katamaranov** [comment]
I looked at the keyboard.h file and didn't find anything similar to Knack or Kback. I still haven't figured out which key is meant by this name.

**Comment by katamaranov** [comment]
Oh, I found ```Knack``` in keyboard.h in the 9front system. But in the description of this project it says that ```nc``` is a file manager for plan9, so I do not know if it is a mistake or not

**Comment by telephil9** [comment]
no mistake here unless you imagine 9front is not plan9... *shrug*
